In [1]:
import numpy as np, pandas as pd
from knn import KNN
from functions import pairwiseDist, prepData
from crossValidate import getCrossValidFolds, crossValidate, tuneK

In [2]:
testX = np.vstack([np.random.randn(8,5)+9, np.random.randn(5,5)+2])
testY = np.array(['B']*8 + ['S']*5)
testPred = np.vstack([np.random.randn(5,5)+9, np.random.randn(2,5)+2])
print(testX)
print(testY)

[[ 8.06335802  8.79459343  8.76963618  9.29465774  8.92997581]
 [ 9.9184858   7.61793164  9.23081607  9.36492384  8.77674563]
 [10.02316492  8.38056287  7.34539767  9.06784205  8.09705132]
 [ 9.5233742   8.83421234  9.10407714  9.76824664  9.29688184]
 [ 9.82927137 10.06394666  7.8907739   8.52669928  8.30888134]
 [ 8.00145052  8.796619    7.56070801  9.91403493  9.05797927]
 [ 8.05809913  7.29344558  8.32922326  9.10898449  8.1581821 ]
 [ 8.38951846  7.88624261  7.59543005  7.41969884  9.63810988]
 [ 1.82686617  3.29748757 -0.23648518  3.01868301  2.84543287]
 [ 1.0776139   1.58739156  1.2758656   0.676572    2.67390846]
 [ 3.9132101   1.62309663  0.8653541   0.85284904  2.57726905]
 [ 1.6500064   1.51827155  3.00376464  0.79600888  1.82454938]
 [ 1.88355036  2.0226918   2.92494179  1.15258018  2.90053692]]
['B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'S' 'S' 'S' 'S' 'S']


In [3]:
KNN(testX, testY, testPred, 3, categorical=True)

array(['B', 'B', 'B', 'B', 'B', 'S', 'S'], dtype='<U1')

In [4]:
ecoliPD = './data/ecoli.data'
ecoliVars = ['seq', 'mcg', 'gvh', 'lip', 'chg', 'aac', 'alm1', 'alm2', 'class']
################################################################################
ecoliMat,ecoliFeat,ecoliY = prepData(ecoliPD, ecoliVars, slice(1,-1), "class", r'\s+')
folds = getCrossValidFolds(ecoliMat, ecoliY, categorical=True)

In [5]:
folds

[array([124,  23, 134, 113,  25, 140, 142,  24,  77,  18, 119,  26,  56,
        128,  89, 136,  65, 114, 117,  98,  40, 120,   1,  95,  16,  10,
         28,  21,  92, 166, 160, 198, 175, 155, 185, 157, 215, 212, 154,
        174, 158, 202, 199, 167, 152, 223, 220, 237, 236, 248, 258, 252,
        225, 241, 276, 277, 265, 264, 281, 297, 322, 299, 295, 309, 334,
        321, 333, 317, 286, 302]),
 array([ 37,  39,  69,  60, 118, 123,  67, 122,  30, 100,   9,  32,  49,
         85,  20,  70, 102, 132,  80,  82,  99,  14, 107,  62,  96,  33,
        106, 129,  75, 203, 162, 189, 177, 200, 171, 218, 217, 161, 196,
        153, 210, 172, 168, 186, 150, 222, 221, 226, 224, 239, 249, 227,
        257, 245, 259, 261, 273, 269, 280, 294, 301, 318, 305, 289, 325,
        292, 331, 296, 291, 315]),
 array([ 54,  50,  84,  19,  91,  74,  55,   2,  72, 116,  22,   7, 141,
        131,  68,   5, 126,  57,  58, 110,  35,  47, 121, 127,  41,  61,
        139,  12, 109, 205, 209, 219, 144, 149, 179, 1

In [6]:
minK,errs = tuneK(ecoliMat, ecoliY, folds, categ=True)
print(minK)

4


In [7]:
crossValidate(ecoliMat, ecoliY, folds, minK, categ=True)

array([0.14285714, 0.18571429, 0.09090909, 0.15384615, 0.12307692])