In [1]:
import numpy as np, pandas as pd

In [159]:
def pairwiseDist(x, y=None):
    if y is None:
        y = x
    return np.sum((x[:,None]-y)**2,axis=2)**0.5

def prepData(dataPathDir, fieldNames, featSlices, labelName, 
             sep=',', transf=None):
    raw = pd.read_csv(dataPathDir , sep=sep, names=fieldNames) # read dlm file
    if isinstance(featSlices, slice):
        dataFeats = fieldNames[featSlices] # list of feature names
    else:
        dataFeats = [fieldNames[i] for i in featSlices]
    if transf is None: # no transformation
        dataMat = raw[dataFeats].values # original values
    elif transf.lower() == 'std' : # if choose to standardize data
        meanVals = raw[dataFeats].mean().values # mean of all features
        stdVals = raw[dataFeats].std().values # standard deviations
        dataMat = (raw[dataFeats].values - meanVals) / stdVals # [x-E(x)]/S(X)
    elif transf.lower() == 'rescale': # rescale to values in [0,1]
        mins = raw[dataFeats].min().values # min of feature vals
        maxs = raw[dataFeats].max().values # max of feature vals
        dataMat = (raw[dataFeats].values-mins) / (maxs-mins) # x-min/range(x)
    else: # error out
        raise Exception('No such transformation available')
    return dataMat,dataFeats,raw[labelName].values

def errRate(pred, actual, categorical=True):
    if categorical: # if categ., return classification err rate
        return sum(pred!=actual) / pred.size
    else: # if numeric, return RMSE
        return np.linalg.norm(pred-actual)/np.sqrt(pred.size)

In [301]:
def mostCommonElem(elems):
    counts = dict() # dict to keep track of counts
    for e in elems: # loop over array
        counts[e] = counts.get(e,0) + 1 # increase count by 1 (def count of 0)
    maxCount = -1
    for e,ct in counts.items(): # loop over counts, set maxCount if count larger
        maxCount = ct if ct > maxCount else maxCount
    # get list of elems which has same count as maxCount (if multiple elems)
    mostFreqElem = [e for e,ct in counts.items() if ct==maxCount]
    return np.random.choice(mostFreqElem) # randomly choose one elemn from all

def kMinValIdx(mat, k):
    mat = np.copy(mat) # create copy of variable
    if mat.size == 1:
        return np.array([[0]]),mat
    if mat.ndim == 1:
        mat = mat.reshape([1,-1])
    idx = np.ones(mat.shape,int).cumsum(axis=1)-1 # rows of idx: 0,1,...,nCol
    
    for it in range(k): # perform k bubbles to get k smallest
        for col in range(mat.shape[1]-it-1):
            toSwap = mat[:,col] < mat[:,col+1] # if elem smaller than next elem
            # swap cols of data matrix and matrix of indices
            mat[np.ix_(toSwap,[col,col+1])] = mat[np.ix_(toSwap,[col+1,col])]
            idx[np.ix_(toSwap,[col,col+1])] = idx[np.ix_(toSwap,[col+1,col])]
    return idx[:,-k:],mat[:,-k:] # return smallest elemenst per row and the idxs

################################################################################
def KNN(trainX, trainY, testX, K, categorical):
    dists = pairwiseDist(testX, trainX) # all pairwise dist of two datasets
    knnIdx,_ = kMinValIdx(dists, K) # idx of K closest data pts in training set
    knnLabels = trainY[knnIdx] # labels of these closest data points
    
    testY = np.empty(testX.shape, trainY.dtype) # pre-allocate test data labels
    if not categorical: # regression, calculate mean
        testY = knnLabels.mean(axis=1) # mean of k-closest label values
    else: # classification, get most common class label
        testY = np.array([mostCommonElem(lab) for lab in knnLabels])
    return testY # return results

In [304]:
def pickAndRemove(arr):
    j = np.random.randint(arr.size)
    return arr[j], np.delete(arr,j)
    
def consistentSubset(trainX, trainY, K=1):
    dists = pairwiseDist(trainX) # all pairwise dist of two datasets
    idx = np.arange(trainX.shape[0]) # construct index of data rows
    Z,idx = pickAndRemove(idx) # randomly pick 1st pt of of subset 

    converged = False
    while not converged:
        converged = True # stop unless a misclassification
        np.random.shuffle(idx) # shuffle sequence of sample to train randomly
        
        for x in idx: # loop over all samples
            nnIdx = kMinValIdx(dists[x,Z], 1)[0] # idx of NN in Z
            nnLabel = trainY[nnIdx].flatten() # label of NN of x in Z
            if nnLabel!=trainY[x]: # if misclassification
                Z = np.hstack([Z,x]) # add to consistent subset
                converged = False # continue training
        idx = np.setdiff1d(idx, Z) # remove training set from samples
        
    return Z, idx
################################################################################
def CNN(trainX, trainY, testX, K):
    subset,dataIdx = consistentSubset(trainX, trainY) # find consist. subset
    
    # use consistent subset as the training set instead of entirety
    return KNN(trainX[subset,:], trainY[subset,:], testX, K, False)

In [310]:
z = consistentSubset(ecoliMat, ecoliY)

(331,)
(336, 7)


In [289]:
testX = np.array([[2,1], [1,2], [2,3], [3,2], [4,1],
                  [5,1.5], [4,2.5], [6,3], [5,4]])
testY = np.array(['r', 'r', 'r', 'r', 'r', 'g', 'g', 'g', 'g'])
consistentSubset(testX, testY)

['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']
['r' 'r' 'r' 'r' 'r' 'g' 'g' 'g' 'g']


(array([8, 5, 6, 7]), array([0, 1, 2, 3, 4]))

In [281]:
def getCrossValidFolds(dataMat, classVec, nFolds=5, categorical=False):
    ''' Cut N-fold cross validation of the data set
    '''
    
    idx = np.arange(dataMat.shape[0]) # construct index of data rows
    if categorical:
        unqs = np.unique(classVec)
        tmpHold = [None] * len(unqs)
        for n,k in enumerate(unqs):
            grpIdx = idx[classVec==k] # idx of all elems in current class
            np.random.shuffle(grpIdx) # permutate idx for random selection
            tmpHold[n] = np.array_split(grpIdx, nFolds) # split: N equals
        chunks = [np.hstack(k) for k in zip(*tmpHold)] # concat sub chunks
    else:
        np.random.shuffle(idx) # random shuffle data
        chunks = np.array_split(idx, nFolds) # split into N equal sized chunks

    return chunks # return the prediction of the last fold

def crossValidate(dataMat, labels, chunks, k, categ):
    err = np.empty(len(chunks))
    
    for ck in range(len(chunks)):
        # get index and dataset for current fold of cross-validation
        trnIdx = np.hstack([x for n,x in enumerate(chunks) if n != ck])
        vldIdx = np.hstack([x for n,x in enumerate(chunks) if n == ck])
        dataTrain,labelTrain = dataMat[trnIdx,:],labels[trnIdx] # training
        dataTest,labelTest = dataMat[vldIdx,:],labels[vldIdx] # validation
        
        pred = KNN(dataTrain, labelTrain, dataTest, k, categorical=categ)
        err[ck] = errRate(pred, labelTest, categorical=categ)
    return err

In [279]:
def tuneK(dataMat, labels, folds, categ):
    Ks = np.arange(1,11)
    err = np.empty(len(Ks))
    
    pick = np.random.randint(len(folds)) # randomly pick fold as validation set
    trnIdx = np.hstack([x for n,x in enumerate(folds) if n != pick]) # train
    vldIdx = np.hstack([x for n,x in enumerate(folds) if n == pick]) # validate
    dataTrain,labelTrain = dataMat[trnIdx,:],labels[trnIdx] # training
    dataTest,labelTest = dataMat[vldIdx,:],labels[vldIdx] # validation
    
    for n,k in enumerate(Ks):
        pred = KNN(dataTrain, labelTrain, dataTest, k, categorical=categ)
        err[n] = errRate(pred, labelTest, categorical=categ)
    
    return Ks[np.argmin(err)], err # return K with smallest error

In [283]:
ecoliPD = './data/ecoli.data'
ecoliVars = ['seq', 'mcg', 'gvh', 'lip', 'chg', 'aac', 'alm1', 'alm2', 'class']
################################################################################
ecoliMat,ecoliFeat,ecoliY = prepData(ecoliPD, ecoliVars, slice(1,-1), "class", r'\s+')
folds = getCrossValidFolds(ecoliMat, ecoliY, categorical=True)

In [284]:
minK,errs = tuneK(ecoliMat, ecoliY, folds, categ=True)
crossValidate(ecoliMat, ecoliY, folds, minK, categ=True)

array([0.15714286, 0.12857143, 0.15151515, 0.09230769, 0.15384615])

In [268]:
firePD = './data/forestfires.data'
fireVars = ['X', 'Y', 'month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp',
           'RH', 'wind', 'rain', 'area']
fireIdx = [0,1] + list(range(4,12))
fireMat,fireFeats,fireY = prepData(firePD, fireVars, fireIdx, "area", transf="rescale")
fireY = np.log(fireY+1)
################################################################################
folds = getCrossValidFolds(fireMat, fireY, categorical=False)

In [282]:
minK,errs = tuneK(fireMat, fireY, folds, categ=False)
np.exp(crossValidate(fireMat, fireY, folds, minK, categ=False))-1

array([1.33034192, 0.91914206, 1.53770281, 1.28881287, 1.29043012])

In [276]:
machPD = './data/machine.data'
machVars = ['vendor', 'model', 'MYCT', 'MMIN', 'MMAX', 'CACH', 'CHMIN', 
             'CHMAX', 'PRP', 'ERP']
################################################################################
machMat,machFeat,machY = prepData(machPD, machVars, slice(2,-2), "PRP", transf='rescale')
folds = getCrossValidFolds(machMat, machY, categorical=False)

In [277]:
minK,errs = tuneK(machMat, machY, folds, categ=False)
crossValidate(machMat, machY, folds, minK, categ=False)

array([57.7579102 , 85.21778822, 56.77461706, 52.70267003, 39.06155243])

In [247]:
minK

6

In [238]:
segPD = './data/segmentation.data'
segVars = ['class', 'cent-col', 'cent-row', 'pixel-count', 'sl-density-5', 
             'sl-density-2', 'vedge-mean', 'vegde-sd', 'hedge-mean', 'hedge-sd',
             'intense-m', 'rawred-m', 'rawblue-m', 'rawgreen-m', 'exred-m', 
             'exblue-m', 'exgreen-m', 'value-m', 'saturate-m', 'hue-m']
segIdx = [1,2] + list(range(4,19))
################################################################################
segMat,segFeat,segY = prepData(segPD, segVars, segIdx, "class", transf=None)
folds = getCrossValidFolds(segMat, segY, categorical=True)

In [239]:
minK,errs = tuneK(segMat, segY, folds, categ=True)
crossValidate(segMat, segY, folds, minK, categ=True)

array([0.14285714, 0.16666667, 0.0952381 , 0.28571429, 0.21428571])

In [20]:
trnIdx = np.hstack([x for n,x in enumerate(folds) if n != 1])
vldIdx = np.hstack([x for n,x in enumerate(folds) if n == 1])

pred = KNN(ecoliMat[trnIdx], ecoliY[trnIdx], ecoliMat[vldIdx], 3)
errRate(pred, ecoliY[vldIdx])

0.15714285714285714

In [76]:
testX = np.vstack([np.random.randn(8,5)+9, np.random.randn(5,5)+2])
testY = np.array(['B']*8 + ['S']*5)
testPred = np.vstack([np.random.randn(5,5)+9, np.random.randn(2,5)+2])
z = pairwiseDist(testPred, testX)
print(z)

[[ 3.7531095   1.90570435  2.35356582  2.78923996  2.75831607  5.09819285
   2.59454517  4.09085054 15.14762401 16.15038255 17.29086775 15.53368289
  15.89654084]
 [ 2.89632479  2.42758659  1.78430884  3.09164191  3.69661392  4.88415513
   2.20077493  2.93689178 16.01803308 16.85705599 18.08449835 16.2482904
  16.6680666 ]
 [ 2.48400306  4.20228236  4.83424079  2.97053469  5.98471444  7.4226921
   3.24846557  2.34355008 13.96268961 14.42267718 15.76245646 13.98130953
  14.53907182]
 [ 4.05646107  3.21798525  3.57839308  4.03044589  6.29779001  6.9612301
   4.18227002  3.3522941  16.50386363 17.35561302 18.59506191 16.63545198
  17.17488197]
 [ 3.77493685  3.13927818  1.78213933  3.03847036  3.19118653  4.1723466
   2.54653494  3.8257698  14.89907238 15.7502842  17.20118056 15.18789626
  15.53537594]
 [15.62919977 14.65630948 16.17242659 14.01604968 14.99672879 17.4843315
  15.2171927  15.29248839  2.15042781  2.21585641  4.3617274   1.96923112
   2.08483425]
 [18.12475458 17.07915063 1

In [287]:
KNN(testX, testY, testPred, 3)

array(['B', 'B', 'B', 'B', 'B', 'S', 'S'], dtype='<U1')