In [2]:
import numpy as np
from functions import prepData, splitData
from crossValidation import crossValidate

In [3]:
carPath = './data/car.data'
carNames = ['buying','maint','doors','persons','lug_boot','safety','accept']
carData, carFeats, acceptVec = prepData(carPath, carNames, slice(-1), 'accept')

(xvData,xvLabel),xvFolds,pruningSet = splitData(carData, acceptVec)
crossValidate(xvData, xvLabel, pruningSet, xvFolds)

(array([0.09615385, 0.13141026, 0.09967846, 0.11935484, 0.14239482]),
 array([0.08653846, 0.12179487, 0.10289389, 0.11935484, 0.10355987]))

In [4]:
segPD = './data/segmentation.data'
segVars = ['class', 'centCol', 'centRow', 'pixelCount', 'slDensity5', 
            'slDensity2', 'vedgeMean', 'vegdeSD', 'hedgeMean', 'hedgeSD',
            'intenseMean', 'rawredMean', 'rawblueMean', 'rawgreenMean',
             'exredMean', 'exblueMean', 'exgreenMean', 'valueMean', 
             'saturateMean', 'hueMean']
segFeatIdx = [1,2] + list(range(4,19))
segData, segFeats, segClass = prepData(segPD, segVars, segFeatIdx, 'class')

(xvData,xvLabel),xvFolds,pruningSet = splitData(segData, segClass)
crossValidate(xvData, xvLabel, pruningSet, xvFolds)

(array([0.16666667, 0.23809524, 0.17142857, 0.25714286, 0.17142857]),
 array([0.16666667, 0.21428571, 0.17142857, 0.25714286, 0.17142857]))