In [1]:
import pandas as pd, numpy as np
import os
from NaiveBayes import NB_Train
from LogisticRegression import softMax, fitLogisticNK
from utilities import normalizeDF, discretizeMean

In [2]:
irisFile = os.path.join('./data/', 'iris.data')
irisName = ['sepalLen', 'sepalWth', 'petalLen', 'petalWth', 'class']
raw = pd.read_csv(irisFile , names=irisName)  # read CSV file
irisTypeVec = raw['class']
irisTypes = pd.concat([raw['class']==x for x in raw['class'].unique()],
                     axis=1).values * 1
feats = irisName[:-1]
irisMat = normalizeDF(raw[feats])

In [3]:
irisMat

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [4]:
irisTypes

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

## Naive Bayes Example

In [5]:
irisDiscMat = discretizeMean(raw[feats])
irisDiscMat

array([[0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1,

In [6]:
NB_Train(irisDiscMat, irisTypes)

(array([0.33333333, 0.33333333, 0.33333333]),
 [array([0.98076923, 0.17307692, 0.98076923, 0.98076923]),
  array([0.48076923, 0.82692308, 0.15384615, 0.21153846]),
  array([0.13461538, 0.65384615, 0.01923077, 0.01923077])])

## Logistic Regression Example

In [7]:
wts,nIter = fitLogisticNK(irisMat, irisTypes, 0.5, trace=True)
print(wts)

Iter #0, error: 1.099889
Iter #1000, error: 0.183436
Iter #2000, error: 0.131070
Iter #3000, error: 0.108378
Iter #4000, error: 0.095452
Iter #5000, error: 0.086984
Iter #6000, error: 0.080945
Iter #7000, error: 0.076385
Iter #8000, error: 0.072799
Iter #9000, error: 0.069892
Iter #10000, error: 0.067481
Iter #11000, error: 0.065442
Iter #12000, error: 0.063692
Iter #13000, error: 0.062170
Iter #14000, error: 0.060834
Iter #15000, error: 0.059650
Iter #16000, error: 0.058591
Iter #17000, error: 0.057640
Iter #18000, error: 0.056779
Iter #19000, error: 0.055995
Iter #20000, error: 0.055280
Iter #21000, error: 0.054623
Iter #22000, error: 0.054017
Iter #23000, error: 0.053458
Iter #24000, error: 0.052938
Iter #25000, error: 0.052455
Iter #26000, error: 0.052005
Iter #27000, error: 0.051584
Iter #28000, error: 0.051189
Iter #29000, error: 0.050818
Iter #30000, error: 0.050469
Iter #31000, error: 0.050139
Iter #32000, error: 0.049828
Iter #33000, error: 0.049534
Iter #34000, error: 0.04925

In [8]:
wts,nIter = fitLogisticNK(irisDiscMat, irisTypes, 0.5, trace=True)
print(wts)

Iter #0, error: 1.095623
Iter #1000, error: 0.453744
Iter #2000, error: 0.450173
Iter #3000, error: 0.448799
Iter #4000, error: 0.448054
Iter #5000, error: 0.447582
Iter #6000, error: 0.447255
Iter #7000, error: 0.447013
Iter #8000, error: 0.446827
Iter #9000, error: 0.446680
Iter #10000, error: 0.446559
Final iteration #10481, error: 0.446509
[[ 2.49565894  2.21340278 -4.72772676]
 [-2.77948555  0.73777199  2.05344766]
 [ 4.55166893 -2.42280476 -2.12450921]
 [-4.57604794  1.24844809  3.31290047]
 [-4.39626349  0.1802881   4.1998419 ]]
