In [1]:
import os
import numpy as np, pandas as pd
from utilities import errRate, normalizeDF, makeClassMat
from crossValidate import getXVFolds
from NN_0hidd import train_0hidd, pred_0hidd
from NN_1hidd import train_1hidd, pred_1hidd
from NN_2hidd import train_2hidd, pred_2hidd

## Data Processing
Read in data, make class and data matrix

In [2]:
irisFile = os.path.join('./data/', 'iris.data')
irisName = ['sepalLen', 'sepalWth', 'petalLen', 'petalWth', 'class']
raw = pd.read_csv(irisFile , names=irisName)  # read CSV file
irisTypes = makeClassMat(raw['class'])
irisMat = normalizeDF(raw[irisName[:-1]])

Divide into 5 folds, take first fold as validation set

In [3]:
folds = getXVFolds(irisMat, irisTypes, categorical=True)
testIdx = folds[0]
trainIdx = np.hstack(folds[1:])
trainData,trainLabel = irisMat[trainIdx],irisTypes[trainIdx]
testData,testLabel = irisMat[testIdx],irisTypes[testIdx]

## Running of Code
Train ANN with 0 hidden layer

In [4]:
wt,nn,err = train_0hidd(trainData, trainLabel, 3, trace=True)
wt

Iter #0, error: 1.100000
Iter #1000, error: 0.077195
Iter #2000, error: 0.074071
Iter #3000, error: 0.071967
Iter #4000, error: 0.070330
Iter #5000, error: 0.068967
Final iteration #5236, error: 0.068674


array([[ -5.6942328 ,   4.49853209,   1.19843556],
       [  9.72297539,  -0.78865438,  -8.92922946],
       [-12.58891082,  -4.04418473,  16.6382307 ],
       [-13.2506071 ,  -5.35664863,  18.59728981],
       [ 10.1280379 ,   7.19002939, -17.31746141]])

In [5]:
pred_0hidd(testData,wt)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

Train ANN with 1 hidden layer, 6 hidden nodes

In [6]:
wt,nn,err = train_1hidd(trainData, trainLabel, 3, 6, trace=True)
wt

Iter #0, error: 1.098656
Final iteration #77, error: 0.084693


(array([[ 3.39946821,  1.43693911, -4.8517327 ],
        [ 3.38667926,  1.44652756, -4.8291338 ],
        [ 4.23751856,  0.61234309, -4.84981597],
        [ 3.37093923,  1.43517644, -4.81730686],
        [ 3.66773783,  1.22155865, -4.89855163],
        [ 3.69408356,  1.20485458, -4.89824446],
        [-8.09398293,  1.34879755,  6.74629599]]),
 array([[ 0.20109822,  0.13904523, -0.50936452,  0.06329672,  0.09296411,
          0.06047301],
        [ 2.2496062 ,  2.16082656,  2.41422178,  2.09220257,  2.44651798,
          2.44483627],
        [-4.20285544, -4.19437932, -4.1194513 , -4.20236567, -4.18932368,
         -4.1881499 ],
        [-4.99484476, -4.99662405, -4.78648785, -5.0023661 , -4.95953702,
         -4.9517947 ],
        [ 3.59990776,  3.67856307,  2.32044529,  3.74999984,  3.14000649,
          3.11061889]]))

In [7]:
pred_1hidd(testData, *wt)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

Train ANN with 2 hidden layers, 6 hidden nodes

In [8]:
wt,nn,err = train_2hidd(trainData, trainLabel, 2, 6, trace=True)
wt

Iter #0, error: 1.098623
Final iteration #460, error: 0.110257


(array([[ 3.1559778 ,  0.58015468, -3.72698151],
        [ 3.1405011 ,  0.64824879, -3.79388671],
        [ 3.12434116,  0.71947282, -3.83342899],
        [ 3.14612629,  0.63151857, -3.77019148],
        [ 3.13592933,  0.61105403, -3.75340837],
        [ 3.11293331,  0.75888943, -3.87005971],
        [-7.45065638,  1.63969413,  5.80544548]]),
 array([[-1.38929367, -1.37375315, -1.36188621, -1.3778579 , -1.36916782,
         -1.35915481],
        [-1.36584352, -1.35227229, -1.33296925, -1.35567808, -1.35295028,
         -1.33396916],
        [-1.35433581, -1.34642938, -1.33856839, -1.34640019, -1.35020981,
         -1.33080123],
        [-1.35355727, -1.3399568 , -1.34365598, -1.35007723, -1.35834743,
         -1.33499585],
        [-1.37661697, -1.38140718, -1.36436972, -1.36905369, -1.37111592,
         -1.36425528],
        [-1.34436539, -1.34240832, -1.33378241, -1.34778974, -1.3405863 ,
         -1.32515109],
        [ 2.14674973,  2.23066801,  2.30025807,  2.20535088,  2.18150372,

In [9]:
pred_2hidd(testData, *wt)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [17]:
int('0') > 9

False