In [51]:
import numpy as np, pandas as pd
from utilities import discretizeMean, oneHot, normalizeDF, makeClassMat

In [45]:
def concateIntercept(x):
    ''' Concatenate Intercept term to input by adding a column of ones to the
    right of the inut data. This is useful for training ANN bias.
    '''
    return np.hstack( [x, np.ones((x.shape[0],1), x.dtype)] )

def sigmoid(x):
    ''' Sigmoid function
    '''
    return 1.0 / ( 1 + np.exp(-x) )

def softMax(x):
    ''' Calculate normalized exponential function for weights and input matrix.
    Returns the normalized exponential probabilities for each classes.
    '''
    pr = np.exp(x) # matrix multiply of x and weight
    return pr / np.sum(pr,axis=1)[:,None]

def crossEntNK(yhat, y):
    ''' Cross Entropy function. Used as the error for multi-class ANN.
    Calculate error across classes for all data points, and return mean err.
    '''
    return np.sum(-y*np.log(yhat), axis=1).mean() # avg error over all points

In [33]:
# K=4, D=3, N=8
x = np.random.randint(5, size=[8,2])
x = concateIntercept(x)
wt = np.random.rand(3,4)*2
print(x)
print(wt)

[[0 3 1]
 [2 1 1]
 [0 0 1]
 [2 4 1]
 [1 2 1]
 [1 3 1]
 [2 3 1]
 [3 0 1]]
[[0.56853127 1.62237228 0.5644002  0.36286161]
 [0.33597739 0.81734471 1.16691202 0.35401111]
 [1.05721528 0.53668889 0.58430757 0.56719117]]


In [44]:
train_0hidd(x, y)

array([[0.08545191, 0.21519172, 0.64409739, 0.05525898],
       [0.09306425, 0.7364292 , 0.1320334 , 0.03847314],
       [0.35335603, 0.20996687, 0.22020709, 0.21647001],
       [0.01918195, 0.64328922, 0.3291581 , 0.00837073],
       [0.10809414, 0.48253421, 0.35348217, 0.05588948],
       [0.06151205, 0.44436648, 0.46173825, 0.03238322],
       [0.03375255, 0.69946356, 0.25231799, 0.0144659 ],
       [0.06260476, 0.878168  , 0.03853398, 0.02069326]])