In [2]:
import numpy as np
import os
import pandas as pd
import functions.winnow as WN # import Winnow
import functions.naiveBayes as NB # import Naive Bayes
import functions.modeling as mdl # import modeling functions

## Lecture Example of Winnow Algorithm ##

In [3]:
testX = np.array([[0,0,0],[0,0,1],[0,1,0],[0,1,1],[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
testY = [0,0,0,1,0,1,0,1]
print(testX)
print(testY)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]
[0, 0, 0, 1, 0, 1, 0, 1]


In [4]:
prm = {'theta':0.5, 'alpha': 2}
WN.WinnowTrain(testX, testY, prm, True)

initial weights: [1. 1. 1.]
[0] no update to weights
[1] new weights: [1.  1.  0.5]
[2] new weights: [1.  0.5 0.5]
[3] no update to weights
[4] new weights: [0.5 0.5 0.5]
[5] no update to weights
[6] new weights: [0.25 0.25 0.5 ]
[7] no update to weights
Final weights: [0.25 0.25 0.5 ]


array([0.25, 0.25, 0.5 ])

## Lecture Example of Naive Bayes Algorithm

In [5]:
testX = np.array([[1,1,1,0,0], [0,1,1,1,0], [0,0,1,1,1], [1,0,0,1,0], 
                  [0,1,1,0,1], [0,1,0,1,0], [1,0,0,0,0], [0,1,0,0,0], 
                  [1,0,1,0,1], [0,1,0,1,0]])
testY = np.array([0,0,0,0,0,1,1,1,1,1])
print(testX)
print(testY)

[[1 1 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [1 0 0 1 0]
 [0 1 1 0 1]
 [0 1 0 1 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 1 0 1]
 [0 1 0 1 0]]
[0 0 0 0 0 1 1 1 1 1]


In [6]:
probs = NB.NB_Train(testX, testY, False)
names = ['x1', 'x2', 'x3', 'x4', 'x5']
mdl.printNBmodel(probs, names)

NB Probabilities of Classes:
   Class  Uncond Pr
0      0        0.5
1      1        0.5

NB Conditional Probabilities of Features:
  features  [C=0,X=0]  [C=0,1=0]  [C=1,X=0]  [C=1,X=1]
0       x1        0.6        0.4        0.6        0.4
1       x2        0.4        0.6        0.4        0.6
2       x3        0.2        0.8        0.8        0.2
3       x4        0.4        0.6        0.6        0.4
4       x5        0.6        0.4        0.8        0.2
